apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: carts-db
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - carts-db.ck-sockshop-staging.gke.demo.keptn.sh
  - carts-db
  http:
  - route:
    - destination:
        host: carts-db.ck-sockshop-staging.svc.cluster.local
